### PR TITLE
show Loop duration in seconds and intervall in minutes, layout of Duration button

### PR DESCRIPTION
**Pull request by mountrcg**
as discussed
Simulator Screen Shot - Dev iPhone 12 mini - 2023-02-08 at 21 24 39

### CODE REVIEW

**Comment by mountrcg** [comment]
there is an issue that you have to leave FAX and bring it forward to have the graph adjust to the statsPanel appearing or disappearing when toggling the DisplayStats setting
I think it has to do with `state.DisplayStatistics` and may be `didAppearTrigger` in `MainChartView.swift`

**Comment by mountrcg** [comment]
also added Loop Rate as successfulNR/288 and cycle through Loop Rate > Loops (successNR + ErrorNr)  > Errors > Loop Rate

**Comment by mountrcg** [comment]
> also added Loop Rate as successfulNR/288 and cycle through Loop Rate > Loops (successNR + ErrorNr)  > Errors > Loop Rate 

question is whether 288 should be used as denominator or # of Readings?

**Comment by mountrcg** [comment]
Added ability to show more loop stats in panel also
https://user-images.githubusercontent.com/539276/218434065-10347f37-1b08-4e04-8a3f-dad69a568c9d.MOV

**Comment by Jon-b-m** [comment]
Missing the source strings. Button text will be auto-formatted  with several lines with this layout. You could add a .lineLimit, but that would truncate the text, which we don't want...

**Pull request closed without merging**
