### PR TITLE
Update settings header with version, build number, branch name, commit ID and copyright notice.

### PR DESCRIPTION
**Pull request by bjornoleh**
Get branch name and commit ID from run script, and display this in settings header together with version and build number, and optional copyright notice string (previously used to set BRANCH in Config.xcconfig).

Edit: Branch name displayed in stats should now also be updated.

### CODE REVIEW

**Comment by bjornoleh** [comment]
B12DC077-6F76-47AB-95E9-48C42223C6B7

**Comment by Jon-b-m** [comment]
Looks a bit busy, no, compared to current "FREEAP X 0.5.5" ?

**Comment by bjornoleh** [comment]
> Looks a bit busy, no, compared to current "FREEAP X 0.5.5" ?

The copyright notification is optional (you can leave it blank, I think, but I might have to change something for that) but it’s a nice option to make a short note about the build. 

With TestFlight distributions, the build number must be incremented, and can now be displayed as well. And getting branch and commit ID automatically is nice too of course. You can easily remove what you might deem excessive though. 


The stats are correctly updated by the way:

"created_at" : "2022-12-30T16:44:10.389Z",
    "Branch" : "bo-11b22ceb",
    "Build_Version" : "0.2.9",
    "Build_Date" : "2022-12-30T16:03:14.000Z",
    "Build_Number" : "2",

**Comment by bjornoleh** [comment]
The COPYRIGHT_NOTICE can now be empty.

**Comment by bjornoleh** [comment]
Added another small fix.

Please note that if building from a branch with uncommitted changes (detached HEAD), it seems the branch name or commit ID is not displayed with this procedure.

If you want to remove some elements from the heading, you can edit this line:

https://github.com/Jon-b-m/freeaps/blob/fabe9ed04efb552cb7b3a2260c4c1368b75b2941/FreeAPS/Sources/Modules/Settings/View/SettingsRootView.swift#L15

**Pull request merged**
