### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by Jon-b-m**

### CODE REVIEW

**Comment by mountrcg** [comment]
Jon, how would I go abou that? On Crowdin I can't see how to change english base entries.
------
by Ivan:
Please, don't change localized keys directly in code. Better change the value on https://crowdin.com/project/freeaps-x
And I prefer that custum insulin settings are not in the main section.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
--------

**Comment by Jon-b-m** [comment]
You can PM me the strings that need to be added and I'll add them to the Base language folder and then Crowdin will update the rest of the necessary files automatically

**Comment by Jon-b-m** [comment]
Aha, I see now. This change you're suggestion requires change to Ivan's code..

**Comment by mountrcg** [comment]
ok, thanks.

**Pull request merged**
