### PR TITLE
dailyTDD in coreData

### PR DESCRIPTION
**Pull request by mountrcg**
so here is a suggestion to compress TDD into dailyTDD. So most probaly it's enogh to only keep 48hrs worth of data in TDD

### CODE REVIEW

**Comment by mountrcg** [comment]
I was also thinking of not pulling 2 TDD's from coreData and checking their dates against each other, but just comparing to the current Day with a single pulled TDD entry and doing it befor you amend the currently calculated TDD from enacted to coreData, which I think you do in line 690-692. Might be more efficient.

**Comment by mountrcg** [comment]
or even better, one could do as in the PR but in the same pull you do for the 2 hour average - then it is one pull less

**Comment by Jon-b-m** [comment]
Please do this instead:
Keep current TDD class. Add Average TDD as a computed property. To calculate the property use sorting/filtering to retrieve an array of the TDDs of **current**  time of day for instance 10 or 14 days back. From this array calculate the average (Sum of TDDs / nr of TDDs). Cache or save this property and save it to tdd_averages.

**Comment by mountrcg** [comment]
I would suggest for day 15 you use the average of the last last 2hr sof rolling 24hr TDD. And for 14 day avg you use the average of TDD day 1-14 . If you want to use the rolling-TDD at 3:15 pm on Day 1-14 you would have to keep all rolling TDD's again for 14 days and most probably have a slipping issue when on day 6 only rolling TDD's at 2:45 or 3:35 are available.

**Comment by Jon-b-m** [comment]
"sof" ? The filtering could use a timespan of 1-2, doesn't need to be exact. Number of days also don't need to be precise, if less than 10 days just use all days currently available in CorData.  If you want a better average with potentially  less error than now, this is  how I think It should be done. But if you're not up for it, I already think current implantations with averaging of all TDD data already is OK as is.

**Comment by mountrcg** [comment]
I am actually not doing it for the weighted average of DynISF, but in order to not deviate from your branch. I need yesterdays TDD and a proper 7 day average to manage TDD with my diet. So I know I cannot burden you with it.

**Comment by mountrcg** [comment]
agreeing not to pursue this in your branch

**Pull request closed without merging**
